Name = "Soup.Cpp"
Language = "C#"
Version = "1.0.0"
Source = [
	"Tasks/BuildTask.cs",
	"Tasks/RecipeBuildTask.cs",
	"Tasks/ResolveDependenciesTask.cs",
	"Tasks/ResolveToolsTask.cs",
]

[Dependencies]
Runtime = [
	{ Reference = "Opal@1.0.1" },
	{ Reference = "Soup.Build@0.1.3", ExcludeRuntime = true },
	{ Reference = "Soup.Build.Extensions@0.1.8" },
	{ Reference = "Soup.Cpp.Compiler@0.1.7" },
	{ Reference = "Soup.Cpp.Compiler.MSVC@0.1.9" },
]