[Projects]
"C#" = [
	{ Name = "Soup.CSharp", Version = "./" },
	{ Name = "Opal", Version = "Opal@1.0.1" },
	{ Name = "Soup.Build", Version = "Soup.Build@0.1.3" },
	{ Name = "Soup.Build.Extensions", Version = "Soup.Build.Extensions@0.1.8" },
	{ Name = "Soup.CSharp.Compiler", Version = "Soup.CSharp.Compiler@0.1.5" },
	{ Name = "Soup.CSharp.Compiler.Roslyn", Version = "Soup.CSharp.Compiler.Roslyn@0.1.6" },
]
