Name = "Soup.CSharp.Compiler"
Language = "C#"
Version = "0.1.1"
Source = [
	"BuildArguments.cs",
	"BuildEngine.cs",
	"BuildResult.cs",
	"CompileArguments.cs",
	"ICompiler.cs",
	"MockCompiler.cs",
]

[Dependencies]
Runtime = [
	{ Reference = "Opal@1.0.1" },
	{ Reference = "Soup.Build@0.1.3", ExcludeRuntime = true },
	{ Reference = "Soup.Build.Extensions@0.1.5" },
]